import { environment } from "src/environments/environment";

const API_ENDPOINT = environment.apiUrl;

export const APIEndPoints = {
    auth: {
        login: environment.apiUrl + '/auth/login',
        refreshToken: environment.apiUrl + '/auth/refresh-token',
        logout: environment.apiUrl + '/auth/logout',
        verifyEmail: environment.apiUrl + '/auth/verify-email',
        updatePassword: environment.apiUrl + '/auth/update-password',
    },
    newUser: environment.apiUrl + '/user/create',
    saveUser: environment.apiUrl + '/user/save',
    editUser:environment.apiUrl + '/user/edit',
    updateUser:environment.apiUrl + '/user/updateuser',
    getLocation:environment.apiUrl + '/auth/slocation',
    
    common: {
        location: `${API_ENDPOINT}/common/location`,
        subLocation: `${API_ENDPOINT}/common/sublocation`,
        allSubLocation: `${API_ENDPOINT}/common/all-sublocation`,
        fileUpload:environment.apiUrl + '/common/upload',
        download: `${API_ENDPOINT}/common/download`,
    },
    newuser: {
        get: `${API_ENDPOINT}/user/list`,
        generateForm: `${API_ENDPOINT}/user/generate-form`,
        save: `${API_ENDPOINT}/user/save`,
        update: `${API_ENDPOINT}/user/updateuser`,
        delete: `${API_ENDPOINT}/user/delete`,
        igtIdAndEmailForm: `${API_ENDPOINT}/user/igt-id-email-form`,
        igtIdAndEmailUpdate: `${API_ENDPOINT}/user/igt-id-email-update`,
        updateStatusUser: `${API_ENDPOINT}/user/update-status`,
    },
    constructural:{
        generateForm: `${API_ENDPOINT}/constructural/generate-form`,
        save: environment.apiUrl + '/constructural/save',
        delete: `${API_ENDPOINT}/constructural/delete`,
        update: `${API_ENDPOINT}/constructural/update`,
    },
    dataManagement:{
        generateForm: `${API_ENDPOINT}/data-management/generate-form`,
        save: environment.apiUrl + '/data-management/save',
        delete: `${API_ENDPOINT}/data-management/delete`,
        update: `${API_ENDPOINT}/data-management/update`,
    },
    networkSetup: {
        getList: `${API_ENDPOINT}/network-setup/list`,
        create: `${API_ENDPOINT}/network-setup/create`,
        update: `${API_ENDPOINT}/network-setup/update`,
        updateIgtId: `${API_ENDPOINT}/network-setup/update-igt-id-email`,
        delete: `${API_ENDPOINT}/network-setup/delete`,
        form: `${API_ENDPOINT}/network-setup/generateForm`,
        formIGT: `${API_ENDPOINT}/network-setup/generateFormIGT`,
        updateStatus:`${API_ENDPOINT}/network-setup/update-status`,
    },
    newHire: {
        get: `${API_ENDPOINT}/newhire/list`,
        create: `${API_ENDPOINT}/newhire/create`,
        save: `${API_ENDPOINT}/newhire/save`,
        edit: `${API_ENDPOINT}/newhire/edit`,
        update: `${API_ENDPOINT}/newhire/updatehire`,
        delete: `${API_ENDPOINT}/newhire/delete`,
        updateStatusHire: `${API_ENDPOINT}/newhire/update-status`,
        generateForm: `${API_ENDPOINT}/newhire/generate-form`,
    },
    locationTransfer:{
        getLocation:`${API_ENDPOINT}/location-transfer/list`,
        update: `${API_ENDPOINT}/location-transfer/update`,
        save: `${API_ENDPOINT}/location-transfer/save`,
        delete: `${API_ENDPOINT}/location-transfer/delete`,
        updateStatus: `${API_ENDPOINT}/location-transfer/update-status`,
        form: `${API_ENDPOINT}/location-transfer/generate-form`,
    },
    terminate: {
        get: `${API_ENDPOINT}/terminate/list`,
        create: `${API_ENDPOINT}/terminate/create`,
        save: `${API_ENDPOINT}/terminate/save`,
        edit: `${API_ENDPOINT}/terminate/edit`,
        update: `${API_ENDPOINT}/terminate/update`,
        delete: `${API_ENDPOINT}/terminate/delete`,
        updateStatus: `${API_ENDPOINT}/terminate/update-status`,
    },
    projectMovement: {
        get: `${API_ENDPOINT}/project-movement/list`,
        create: `${API_ENDPOINT}/project-movement/create`,
        save: `${API_ENDPOINT}/project-movement/save`,
        edit: `${API_ENDPOINT}/project-movement/edit`,
        update: `${API_ENDPOINT}/project-movement/update`,
        delete: `${API_ENDPOINT}/project-movement/delete`,
        updateStatus: `${API_ENDPOINT}/project-movement/update-status`,
    },
    shortTrip: {
        get: `${API_ENDPOINT}/short/list`,
        create: `${API_ENDPOINT}/short/createtrip`,
        save: `${API_ENDPOINT}/short/save`,
        edit: `${API_ENDPOINT}/short/edit`,
        update: `${API_ENDPOINT}/short/updatetrip`,
        delete: `${API_ENDPOINT}/short/delete`,
        updateStatus: `${API_ENDPOINT}/short/update-status`,
    },
    fileUpload:environment.apiUrl + '/short/upload',
    inactivate: {
        getList: `${API_ENDPOINT}/inactivate/list`,
        create: `${API_ENDPOINT}/inactivate/create`,
        update: `${API_ENDPOINT}/inactivate/update`,
        delete: `${API_ENDPOINT}/inactivate/delete`,
        form: `${API_ENDPOINT}/inactivate/generate-form`,
        updateStatus: `${API_ENDPOINT}/inactivate/update-status`,
    },
    reactivate: {
        get: `${API_ENDPOINT}/reactivate/list`,
        create: `${API_ENDPOINT}/reactivate/create`,
        save: `${API_ENDPOINT}/reactivate/save`,
        edit: `${API_ENDPOINT}/reactivate/edit`,
        update: `${API_ENDPOINT}/reactivate/update`,
        delete: `${API_ENDPOINT}/reactivate/delete`,
        updateStatus: `${API_ENDPOINT}/reactivate/update-status`,
    },
    generateActivity: {
        getList: `${API_ENDPOINT}/generate-activity/list`,
        sendToGenerateActivity: `${API_ENDPOINT}/generate-activity/send-to-generate-activity`,
        downloadGenerateActivity: `${API_ENDPOINT}/generate-activity/download-generate-activity`,
        updateStatus: `${API_ENDPOINT}/generate-activity/update-status`,
        downloadGenerateData: `${API_ENDPOINT}/generate-activity/downloadGenerateData`,
    },
    reports: {
        create: `${API_ENDPOINT}/reports/create`,
        generate: `${API_ENDPOINT}/reports/generate`,
    },
    dashboard : {
        getDetails: `${API_ENDPOINT}/dashboard/details`,
    },
    accountSetting: {
        save: `${API_ENDPOINT}/account-setting/register`,
        generateForm: `${API_ENDPOINT}/account-setting/generate-form`,
        getAppUserList: `${API_ENDPOINT}/account-setting/app-user-list`,
        getAccountListByModule: `${API_ENDPOINT}/account-setting/account-setting-list`,
        getManagerDetailsList: `${API_ENDPOINT}/account-setting/manager-details-list`,
        saveManagerDetails: `${API_ENDPOINT}/account-setting/save-manager-details`,
        generateManagerForm: `${API_ENDPOINT}/account-setting/generate-manager-form`,
        updateManagerDetails: `${API_ENDPOINT}/account-setting/update-manager-details`,
        deleteManagerDetails: `${API_ENDPOINT}/account-setting/delete-manager-details`,
    }
}